services:
  mysql:
    image: mysql:8.0
    container_name: estoque-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque
      MYSQL_USER: estoque_user
      MYSQL_PASSWORD: estoque_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Estoque-Backend
    container_name: estoque-backend
    ports:
      - "8081:80"
    volumes:
      - ./Estoque-Backend:/var/www/html 
    depends_on:
      - mysql

  frontend:
    build: ./Estoque-Frontend
    container_name: estoque-frontend
    ports:
      - "5174:5173"
    volumes:
      - ./Estoque-Frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  mysql_data:
